services:
  postgres:
    image: postgres:16
    container_name: jarvis-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: jarvisdb
      POSTGRES_USER: jarvis
      POSTGRES_PASSWORD: spring123
    ports:
      - "5432:5432"
    volumes:
      - jarvis_data:/var/lib/postgresql/data

volumes:
  jarvis_data: