services:
  postgres:
    image: postgres:16
    container_name: jarvis-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: jarvisdb
      POSTGRES_USER: jarvis
      POSTGRES_PASSWORD: spring123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - jarvis-network

volumes:
  postgres_data:
    driver: local

networks:
  jarvis-network:
    driver: bridge